### PR TITLE
Display seconds in the status activity

### PR DESCRIPTION
**Pull request by oliv3**
Useful when update frequency is less than 60 seconds

### CODE REVIEW

**Comment by oliv3** [comment]
How is this useless ?

**Comment by tananaev** [comment]
Have you seen your commit?

**Comment by tananaev** [comment]
Can you please provide a screenshot of what it looks like on a small screen.

**Comment by oliv3** [comment]
Erm, seriously ?
Can do that. Your definition of "small" ?

**Comment by oliv3** [comment]
traccar-qvga

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
