### PR TITLE
Fix battery level reporting

### PR DESCRIPTION
**Pull request by oliv3**
Client sends battery _level_.

### CODE REVIEW

**Comment by tananaev** [comment]
We shouldn't change it. This was original key in OsmAnd protocol.

**Comment by oliv3** [comment]
@tananaev Also, this will correctly end in Position.KEY_BATTERY_LEVEL without changing code server-side.

**Comment by tananaev** [comment]
I don't see any good reason for changing protocol. There might be some clients that use old format.

**Comment by oliv3** [comment]
It is backward-compatible. Nothing has to be changed server-side. It will work for old clients. Or did I miss something ?

**Comment by tananaev** [comment]
Yes, but why do you want to change it then if we still need to handle it on the server side?

**Comment by oliv3** [comment]
Nothing has to be changed server-side.

**Comment by tananaev** [comment]
If you didn't get my question, I'm asking why you want to change it in the client if you don't plan to change anything on the server side?

**Comment by oliv3** [comment]
If you don't read what I write, then please reopen the issue. I'm not done with this one yet. So I'll carefuly explain this to you, but later. Thanks.

**Comment by tananaev** [comment]
I will re-open when you provide compelling reasons for this change.

**Comment by oliv3** [comment]
I'll sure will.

**Comment by oliv3** [comment]
Hi @tananaev 
Please re-open, here is a compelling reason: OsmAnd client **never**, **ever** sent battery information.
Reference: https://github.com/osmandapp/Osmand/blame/8650ecce1d35fb0f5ec94d1401aa8496075f3276/OsmAnd/src/net/osmand/plus/activities/LiveMonitoringHelper.java

**Comment by tananaev** [comment]
It was added for a reason. Possibly it was just a key we chose in the old version of Traccar. Either way I don't see any good reason for changing it. Why are you so obsessed with changing it? What is the reason?

**Comment by oliv3** [comment]
Simply for a logical reason ?
Why do you keep insisting sending apples when they should be pears ?
What is the reason for
```public static final String KEY_BATTERY_LEVEL = "batteryLevel"; // percentage``` ?
Please explain.

**Comment by oliv3** [comment]
Also please explain what was the reason. OsmAnd client is 7 years old, when your implementation of the protocol dates back to 2013.

**Comment by tananaev** [comment]
I don't remember what was the reason for this name. Anyway, here are the reasons for keeping it as it is:

1. There are other server implementations that support Traccar Client and this change will break their implementations.
2. There are old versions of Traccar Client (and possibly other apps) that use original key, so even if we change it, we can't remove this case on the server side.

On the server side we support two versions on battery value (percentage and voltage). OsmAnd protocol supports only one version (percentage), so I don't see any reason for changing it.

**Pull request closed without merging**
